spring.application.name=minecraft-mods-catalog
server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/minecraft_mods}
spring.datasource.username=${USERNAME}
spring.datasource.password=${USERPASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initializationFailTimeout=60000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.open-in-view=false
spring.jackson.deserialization.accept-single-value-as-array=true
spring.data.web.pageable.one-indexed-parameters=true

# Logging configuration
logging.level.root=INFO
logging.level.com.example.minecraftmodscatalog=DEBUG
logging.level.com.example.minecraftmodscatalog.aspect=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web=INFO
logging.config=classpath:logback.xml

# Swagger/OpenAPI configuration
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.Operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.deep-linking=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true

