spring.application.name=minecraft-mods-catalog
server.port=8081

spring.datasource.url=${DB_URL:jdbc:h2:mem:minecraft_mods;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false}
spring.datasource.username=${USERNAME:sa}
spring.datasource.password=${PASSWORD:}
spring.datasource.driver-class-name=${DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.hikari.initializationFailTimeout=60000

spring.jpa.database-platform=${JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.open-in-view=false
spring.jackson.deserialization.accept-single-value-as-array=true
spring.data.web.pageable.one-indexed-parameters=true

# Logging configuration
logging.level.root=INFO
logging.config=classpath:logback.xml

# Swagger/OpenAPI configuration
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.Operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.deep-linking=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
